name: Build Android SO

on:
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build cmake unzip

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 34
        ndk-version: 26.1.10909125
        cmake-version: 3.22.1

    - name: Build with CMake
      run: |
        mkdir build && cd build
        cmake \
          -DANDROID_ABI=armeabi-v7a \
          -DANDROID_PLATFORM=android-21 \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
          ..
        make -j$(nproc)

    - name: Upload SO artifacts
      uses: actions/upload-artifact@v3
      with:
        name: android-libs
        path: |
          build/**/*.so
          
