name: Build APK with Capacitor

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Capacitor and Android platform
        run: |
          npm init -y
          npm install @capacitor/core @capacitor/cli @capacitor/android

      - name: Initialize Capacitor
        run: |
          npx cap init "Bobble Shooter" "com.ticnocity.bobbleshooter" --web-dir=www

      - name: Prepare Web Files
        run: |
          mkdir -p www
          rsync -av --exclude=www ./ www/

      - name: Sync Android Project
        run: npx cap sync android

      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: bobble-shooter-apk
          path: android/app/build/outputs/apk/release/*.apk
          
