name: Build APK with Capacitor

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create package.json
        run: |
          if [ ! -f package.json ]; then
            echo '{"name": "bobble-shooter", "version": "1.0.0"}' > package.json
          fi

      - name: Install Capacitor and Android
        run: |
          npm install @capacitor/core @capacitor/cli @capacitor/android

      - name: Initialize Capacitor
        run: |
          npx cap init "Bobble Shooter" "com.ticnocity.bobbleshooter" --web-dir=www

      - name: Prepare Web Files
        run: |
          mkdir -p www
          rsync -av --exclude=www ./ www/

      - name: Add Android Platform
        run: npx cap add android

      - name: Fix Gradle Java Version
        run: |
          sed -i 's/JavaVersion.VERSION_21/JavaVersion.VERSION_17/g' android/app/build.gradle || true
          sed -i 's/JavaVersion.VERSION_21/JavaVersion.VERSION_17/g' android/build.gradle || true

      - name: Sync Android Project
        run: npx cap sync android

      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: bobble-shooter-apk
          path: android/app/build/outputs/apk/release/*.apk
          
